# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thank you for reporting your issue! Someone will get back to you shortly as possible! 

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
   ğŸ’– Thanks for opening this pull request! ğŸ’–
   
  Things that will help get your PR across the finish line:
  
  - [ ] Document any changes you've made.
  - [ ] Include tests when adding/changing behavior.
  - [ ] Include screenshots and animated GIFs whenever possible.


# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰

# It is recommended to include as many gifs and emojis as possible!
